### ISSUE TITLE
SI: Button Labels Disappear in Some Themes

### ISSUE THREAD

**Issue by hismightiness** [UpendoVentures/Upendo-Dnn-PageManager#23]
## Describe the bug
Within the pop-up boxes, the text within the buttons is not always visible. I believe this is due to the text and background both being white in some states. Or, it may be a focus issue.  

## Software Versions
- DNN: 09.06.02 (Evoq Content)  
- Module: 01.00.01

## To Reproduce  
1. Open one of the pop-up boxes  
2. Click on the button(s)  
3. Close the popup box  
4. Reopen the popup box.  
5. The button text is not visible.  

## Expected behavior  
Button text should always be visible, regardless of the state.  

## Actual Behavior  
The text disappears for some buttons.  

## Screenshots
![image](https://user-images.githubusercontent.com/938023/134591079-9d809e4d-9285-4163-be8d-d9092cd4f2cb.png)
  

## Additional context  
There is a conflict with another CSS. This is suppsed to style call to action buttons and footer links:  

```  
a.button--cta:visited, a.button:visited, a.button:focus, .footer__area a:visited {
  color: #fff;
}
```  

However, there does not appear to be a color specification your css for visited and focus states. There are BG and font-family specifications.   

```  
a[_ngcontent-wrh-c77]:focus, a[_ngcontent-wrh-c77]:hover, a[_ngcontent-wrh-c77]:visited {
  text-decoration: none;
  font-family: Roboto,Helvetica Neue,sans-serif;
  background: #fff;
}  
```

**Comment by erw13n** [comment]
Commit added.

**Comment by hismightiness** [comment]
We always need to have pull requests and never direct commits.

**Comment by erw13n** [comment]
PR #36
