### ISSUE TITLE
SI: Fix Roles and Permissions

### ISSUE THREAD

**Issue by hismightiness** [UpendoVentures/Upendo-Dnn-PageManager#26]
## Describe the bug
Roles/Permissions – This feature does not appear to work. The module does not save the changes.  

## Software Versions
- DNN: 09.06.02 (Evoq Content)  
- Module: 01.00.01  

## To Reproduce  
1. Open Roles/Permissions  
2. Make a change  
3. Click Edit  
4. Nothing happens  

## Expected behavior
The changes are saved.  

## Actual Behavior  
Changes are not saved.  

## Screenshots
![image](https://user-images.githubusercontent.com/938023/134592220-ce60d9f3-d904-498a-b1bb-9dae42d99329.png)

## Additional context  
The permissions grid was supposed to be read-only in this release.  Adding the ability to edit this feature is a potential enhancement for a later release.

**Comment by erw13n** [comment]
Nothing been implement for saving permissions.
Require development on API & Client App Services for saving permissions.

**Comment by hismightiness** [comment]
@erw13n Please re-read the issue.  I think you missed the part after the screenshot.

**Comment by erw13n** [comment]
Commit been made for it to **disable "Edit" button**.

**Comment by hismightiness** [comment]
We need a pull request instead. ☹

**Comment by hismightiness** [comment]
Not only should the edit button be disabled, but so should the checkboxes.  Everything should be read-only for permissions.

**Comment by erw13n** [comment]
PR #36 only for disable Edit button
