### ISSUE TITLE
SI: Add Icon Descriptions

### ISSUE THREAD

**Issue by hismightiness** [UpendoVentures/Upendo-Dnn-PageManager#33]
## Describe the bug
There is no way to know what the icons are supposed to do. We need a tool tip or mouseover effect that will show what each icon does. It can be as simple as some text that says “Hide from Menu”,  “Disable Page”, etc.  

## Software Versions
- DNN: 09.06.02 (Evoq Content)  
- Module: 01.00.01  

## To Reproduce
1. Hold your mouse over the icons.  

## Expected behavior
Text will appear to show the function for each of the icons.  

## Actual Behavior
No text appears when you hover over the icons.  Therefore, there's no way to know their intent.

**Comment by erw13n** [comment]
The last icon on table don't have Click function, it use to display status of "Page has been published" or Not.
And the icon reversed. It should display Checkmark instead of Uncheck for published page.

**Comment by erw13n** [comment]
Commit been made for this change.

**Comment by hismightiness** [comment]
We always need a pull request for all projects.

**Comment by erw13n** [comment]
PR #36

**Comment by hismightiness** [comment]
This has tested as resolved.
