### ISSUE TITLE
SI: Modules Pop-Up No Scroll

### ISSUE THREAD

**Issue by hismightiness** [UpendoVentures/Upendo-Dnn-PageManager#34]
## Describe the bug  
If you click the Gear icon and the popup box is really long, it extends off the page. There is no way to view modules below the fold. We’ll need a scroll bar on that box.  

## Software Versions  
- DNN: 09.06.02 (Evoq Content)  
- Module: 01.00.01  

## To Reproduce  
1. On our DEV server, find the FLC home page in the module.  
2. Click on the Gear Icon.  
3. Note that you can not scroll down to see all the modules.  

## Expected behavior
Able to use a scroll bar within the pop-up box to allow you to see all modules.  

## Actual Behavior  
No scroll bar.  

## Screenshots  
![image](https://user-images.githubusercontent.com/938023/134595287-1a0cfc13-87b5-41de-85d9-4977b6f7bb89.png)

**Comment by erw13n** [comment]
Commit been made for it.

**Comment by hismightiness** [comment]
We need a pull request instead. ☹

**Comment by erw13n** [comment]
PR #36
