### ISSUE TITLE
SI: Replace Gear Icon

### ISSUE THREAD

**Issue by hismightiness** [UpendoVentures/Upendo-Dnn-PageManager#35]
## Is your feature request related to a problem?  
Gear Icon - The Gear icon does not reflect that function. The function is to view modules on the page.  

## Describe the solution you'd like  
Use a three-dimensional box or a group of three-dimensional boxes instead.  

## Describe alternatives you've considered  
Here are examples of what to use instead.  
![image](https://user-images.githubusercontent.com/938023/134595657-b3b224a6-27f3-4338-a75b-2182e56b60cd.png)
![image](https://user-images.githubusercontent.com/938023/134595663-1cd57450-3a34-4d15-8377-24e69f2a17e3.png)

**Comment by erw13n** [comment]
What about this one ?
![image](https://user-images.githubusercontent.com/792847/134919081-a7d5ebe3-cd6c-4462-b36f-437e3891947b.png)

I can grab the svg from https://iconmonstr.com/cube-18-svg/

**Comment by hismightiness** [comment]
Something like that, but as an icon if possible.

**Comment by erw13n** [comment]
![image](https://user-images.githubusercontent.com/792847/135321296-48d7a7dd-71cf-4722-bb3e-d6434c23441c.png)

The only similar icon at Material Icon is this one, I'll replace it with this for now.

**Comment by erw13n** [comment]
Commit been made for this change.

**Comment by hismightiness** [comment]
A commit?  We always need a pull request instead.  ☹️

**Comment by erw13n** [comment]
PR #36
