### ISSUE TITLE
SI: Indexed Pages and Non-Indexed Pages Have the Same Icon

### ISSUE THREAD

**Issue by WillStrohl** [UpendoVentures/Upendo-Dnn-PageManager#60]
## Describe the bug
When a page is set to "allow indexing" the index icon in the page manager should be the magnifying glass with a plus icon on it.  However, this icon is always showing all pages as not allowing index to occur.  

## Software Versions
- DNN: 09.09.01  
- Module: 01.00.02  

## To Reproduce  
1. Install DNN, then install this module and add it to a page.  
2. Add a few pages.  
3. Find a page that is not allowing indexing.  
4. Set the page to index.  

## Expected behavior  
The magnifying glass icon should have been the one with a minus symbol before the update, and has the plus symbol in the icon after the update.  

## Actual Behavior  
The icon has the minus sign regardless of the SEO setting status.  

## Error log  
No errors found.  

## Additional context
Sponsored update.  

At first glance, this might be a minor bug in the DNN API, but this needs to be verified.  

## Screenshots  
![image](https://user-images.githubusercontent.com/938023/142078557-29707e06-29f9-4dcf-958f-171ce2b0ee4a.png)

![image](https://user-images.githubusercontent.com/938023/142078649-7d8aa800-646f-4110-932b-f1c857274260.png)

![image](https://user-images.githubusercontent.com/938023/142078741-29b27138-ce69-45cf-9c4c-d24bb4f44444.png)

**Comment by WillStrohl** [comment]
@ArielBlanco1990  I just reviewed the PR.  It appears that instead of just fixing the icon, you also turned this into a new feature... Now, the icon should not only show the correct icon per the page's index setting, but it should now toggle the index setting on double-click.  

Am I seeing this correctly?

**Comment by ArielBlanco1990** [comment]
Yes @WillStrohl, it is right. I had put it in the comments. This was not part of the task but I thought it necessary since we would have a new functionality and if we need to change the state of the page we could do it from the table without having to do it through the PersonBar. If you don't approve this change without problem I can revert it and leave only the icon, this would not take me any time.
