### ISSUE TITLE
Module shows no data

### ISSUE THREAD

**Issue by HZass** [UpendoVentures/Upendo-Dnn-PageManager#62]
## Describe the bug
I expect that the module would show a listing of pages.  However, it only shows the headings and that flashes by and then there is no information on the screen, except the search box.

## Software Versions
- DNN: 09.06.04
- Module: Lates version

## To Reproduce
1. Set up a new page, in any template or format
2.Add the module to the page, while logged in as root
3. No information shows up.
4. Try a hard refresh
5. The listing report headings are displayed for a short time.

## Expected behavior
The module should, I think, show a listing of pages

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.
There is no log entry and debug DLLs are not available

**Comment by WillStrohl** [comment]
Hello @HZass ...  Thank you for reporting an issue.  Unfortunately, there aren't enough details for us to duplicate the issue in a clean instance of DNN.  This might be unique to your environment.  Would you be able to provide any additional details to help us understand the issue you've run into?

**Comment by skadera** [comment]
@WillStrohl  We are seeing this issue on child portals. The module works so-so on the parent but not the children. 

![page-manager-screenshot](https://user-images.githubusercontent.com/18075522/158625328-5946ef18-e86e-4913-a8b7-69d217677145.JPG)

**Comment by skadera** [comment]
@WillStrohl  Here's a video that shows the issue on the parent site. When I switch to view 100 records and change the page title the page refreshes and the data does not come back. Also, when adding a "&" to the page title, nothing happens. The page title does not change. 

See video here: https://web.microsoftstream.com/video/adfd5c1f-0356-4732-9be2-1a47a19f9c00

**Comment by jwbodine** [comment]
@WillStrohl I have fixed this issue and another issue in my local instance.  If you have a few minutes at some point to connect I'd like to show you the issues and my fixes.

**Comment by WillStrohl** [comment]
> @WillStrohl I have fixed this issue and another issue in my local instance. If you have a few minutes at some point to connect I'd like to show you the issues and my fixes.

Would you be able to submit a pull request?  If you'd like to submit a video here, please feel free.  We try to keep communications about these kinds of updates in an open-source project in the same place as the project itself.  I hope you understand.

**Comment by WillStrohl** [comment]
@jwbodine I just wanted to check in with you.  Were you open to contributing your fix back to the project as a pull request?  It would be nice to roll this out to everyone else that might be using this module.  :)

**Comment by alejoroman0605** [comment]
Hi @HZass i created a clean DNN instance and multiple parent and child websites on that single DNN instance. I installed the module on each page created. I created another new DNN instance and run the process again, the error shown was not reproduced. I also checked the front-to-backend requests and server responses while installing that module and found no errors.
@HZass we have made fixes, you can download the latest version of the module and try again, because the fixes may have solved this problem as well.

**Comment by WillStrohl** [comment]
@HZass As Alejandro mentioned, this issue may have inadvertently been fixed as part of another update recently.  Can you please see if you can reproduce this still after upgrading?  If you still can, we may need an updated list of reproduction steps and/or additional environmental details to see if we can reproduce the issue.

**Comment by WillStrohl** [comment]
Closing as stale, since there is no response since Jan 11.
