### ISSUE TITLE
SEO Defaults Are Wrong

### ISSUE THREAD

**Issue by WillStrohl** [UpendoVentures/Upendo-Dnn-PageManager#97]
## Describe the bug
The SEO filter is supposed to default to being on, with Title and Description set as the default.  None of the fields are enabled by default.  

## Software Versions
- DNN: 09.10.00
- Module: 01.01.01

## To Reproduce
1. Install the module.  
2. If necessary, add some pages.  
3. Add the Page Manager to any page.  
4. View the module on the page.  

## Expected behavior
There should be a listing of pages, and the SEO filter should be available, but not turned on.  The `Title` and `Description` should be selected in the `QuickSettings` view.  Those values should continue to save to the module settings as they currently are.  However, when the SEO filter is toggled on or off, this state should be saved and used on subsequent page loads, using a secure cookie that expires in 90 days.  

These default values are only applicable to a clean installation.  If someone has saved a new default, that should be respected.  (A clean installation won't have any settings already saved.)  

## Actual Behavior  
The default is set to not filter by any value.

**Comment by ArielBlanco1990** [comment]
@WillStrohl This Issue was solved in PR #99 
Close #99

**Comment by WillStrohl** [comment]
Thank you for letting me know.  I'll try testing it again soon,
